// <auto-generated>
//   This file was generated by a tool; you should avoid making direct changes.
//   Consider using 'partial classes' to extend these types
//   Input: BattleMessage.proto
// </auto-generated>

#region Designer generated code
#pragma warning disable CS0612, CS0618, CS1591, CS3021, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
[global::ProtoBuf.ProtoContract(Name = @"PB_Vector2D")]
public partial class PBVector2D : global::ProtoBuf.IExtensible
{
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    [global::ProtoBuf.ProtoMember(1, Name = @"x")]
    public long X { get; set; }

    [global::ProtoBuf.ProtoMember(2, Name = @"y")]
    public long Y { get; set; }

}

[global::ProtoBuf.ProtoContract(Name = @"PB_Input")]
public partial class PBInput : global::ProtoBuf.IExtensible
{
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    [global::ProtoBuf.ProtoMember(1, Name = @"index")]
    public uint Index { get; set; }

    [global::ProtoBuf.ProtoMember(2, Name = @"type")]
    public InputType Type { get; set; }

    [global::ProtoBuf.ProtoMember(3)]
    public PBVector2D inputDir { get; set; }

    [global::ProtoBuf.ProtoMember(4)]
    public uint Key
    {
        get => __pbn__Key.GetValueOrDefault();
        set => __pbn__Key = value;
    }
    public bool ShouldSerializeKey() => __pbn__Key != null;
    public void ResetKey() => __pbn__Key = null;
    private uint? __pbn__Key;

}

[global::ProtoBuf.ProtoContract(Name = @"S2C_FrameMessage")]
public partial class S2CFrameMessage : global::ProtoBuf.IExtensible
{
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    [global::ProtoBuf.ProtoMember(1)]
    public ulong frameId { get; set; }

    [global::ProtoBuf.ProtoMember(2, Name = @"messages")]
    public global::System.Collections.Generic.List<PBInput> Messages { get; } = new global::System.Collections.Generic.List<PBInput>();

}

[global::ProtoBuf.ProtoContract(Name = @"C2S_Input")]
public partial class C2SInput : global::ProtoBuf.IExtensible
{
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    [global::ProtoBuf.ProtoMember(1)]
    public PBInput playerInput { get; set; }

}

[global::ProtoBuf.ProtoContract()]
public enum InputType
{
    MoveBegin = 0,
    MoveEnd = 1,
    KeyDown = 2,
    KeyUp = 3,
}

#pragma warning restore CS0612, CS0618, CS1591, CS3021, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
#endregion
